# Generated by Django 4.0.4 on 2022-08-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(default='https://www.youtube.com/watch?v=JblrN5oNse4&ab_cha', max_length=256)),
                ('post_type', models.CharField(default='youtube', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='Insert youtube comments', max_length=256)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_comment', to='sentiment.postlink')),
            ],
        ),
    ]
