# Generated by Django 4.0.4 on 2022-08-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_postlink_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlink',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='post_url',
            field=models.CharField(default='https://www.youtube.com/', max_length=256),
        ),
    ]
