"""
Django settings for BusinessSentiment project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7iru#h6x&g$m45ixi1au#=%)))!-bg+gt*t!a_6114_3ntg=1@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sentiment'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sentimentAnalysis.urls'

# TWITTER_CONSUMER_KEY = 'Kmdm3BgHt7Qt5lFkiIJgVw402'
# TWITTER_CONSUMER_SECRET = 'tWzooq0YbtxJXrJAcqrIJVTzXdo10TZzb5TwWutxv5PNXtEaKj'
# TWITTER_ACCESS_TOKEN = '943100209785077760-TOx2RSACitTVddMj99lLW6vwSr3Y9BX'
# TWITTER_ACCESS_TOKEN_SECRET = 'jEKHx8sbl4T5Jy6eJrDYxVz57Fj8vjDYt5xKas0JOR8nF'


# TWITTER_CONSUMER_KEY = 'LApMQSUqV0T63jwYMOaeZ68Aq'
# TWITTER_CONSUMER_SECRET = '5HyAXqhk2138Hj7czJAZI1TUhsWIJZ5b5NOhf6U5onoZ2VUH10'
# TWITTER_ACCESS_TOKEN = '1259026495760142336-tUhgY3VMDdXhOrLmS9wIdyrKDv88Jp'
# TWITTER_ACCESS_TOKEN_SECRET = 'DM0tCA2c3PDhiFeXPsnBvkG1EOm7kc3UetxfWBUu88Ye5'


TWITTER_CONSUMER_KEY = 'V5upfWiRwHa5O912S4bUdeB9r'
TWITTER_CONSUMER_SECRET = 'E9w8aKmc7gPYSS1yoMWMgSUPtAWeNUVSqFnSGMRSf9gN0XMIoI'
TWITTER_ACCESS_TOKEN = '1259026495760142336-A5dhGQLWHf2tYOOrcQ2CYf7lmlE0cK'
TWITTER_ACCESS_TOKEN_SECRET = '8WLdXVB3IB9iyZHceYM9qZechoFgDUQBGR2A39XuYnuYF'

YOUTUBE_API_KEY = 'AIzaSyBTPGddJsNUFeOMuiErEbo_JDsW7Y65ArM'
COMMENTS_SIZE = 200

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sentimentAnalysis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'sentiment.User'
LOGIN_URL = '/sentiment/login/'
LOGOUT_REDIRECT_URL = "/sentiment/index/"
# LOGIN_REDIRECT_URL = "/"


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = ''
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
